openapi: 3.0.1
info:
  title: CodeBuddies User API Specs for Reset-Password
  description: API for password reset.
  version: 1.0.0
servers:
  - url: "http://localhost:3000"
    description: Local development environment
paths:
  /{id}:
    put:
      summary: Reset password
      description: Resets a user's password.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          examples:
            example1:
              value: "60d...abcdef123456"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
            examples:
              example1:
                value:
                  newPassword: "newPassword123"
      responses:
        "200":
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
              examples:
                example1:
                  value:
                    status: 200
                    message: "Password changed"
        "400":
          description: Password not changed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
              examples:
                example1:
                  value:
                    status: 400
                    message: "Password not changed"